[general]
live_config_reload = true
import = [
	"~/.config/alacritty/themes/kanagawa_dragon.toml"
]

[window]
opacity = 0.85
blur = true
decorations_theme_variant = "Dark"

[font]
size = 15

[terminal]
shell = "nu"
