local fzflua = require("fzf-lua")

vim.keymap.set("n", "<leader>z", fzflua.zoxide, { desc = "fzf-lua: zoxide" })
vim.keymap.set("n", "<leader>,", fzflua.files, { desc = "Find files" })
vim.keymap.set("n", "<leader>rg", fzflua.live_grep, { desc = "Grep for string" })
vim.keymap.set("v", "<leader>rg", fzflua.live_grep, { desc = "Grep for string" })
vim.keymap.set("n", "<leader>gb", fzflua.git_branches, { desc = "List git branches" })
vim.keymap.set("n", "<leader>ldc", fzflua.dap_commands, { desc = "List dap commands" })
vim.keymap.set("n", "<leader>bl", fzflua.git_blame, { desc = "Blame line" })
vim.keymap.set("n", "<C-e>", fzflua.marks, { desc = "List marks" })
vim.keymap.set("n", "<leader>gs", fzflua.grep_cword, { desc = "Grep for word under cursor" })
vim.keymap.set("v", "<leader>gs", fzflua.grep_visual, { desc = "Grep for word under cursor" })

-- Lsp keymaps
vim.keymap.set("n", "gd", fzflua.lsp_definitions, { desc = "[G]oto [D]efinition" })
vim.keymap.set("n", "gr", fzflua.lsp_references, { desc = "[G]oto [R]eferences" })
vim.keymap.set("n", "gI", fzflua.lsp_implementations, { desc = "[G]oto [I]mplementation" })
vim.keymap.set("n", "gi", fzflua.lsp_implementations, { desc = "[G]oto [I]mplementation" })
vim.keymap.set("n", "<leader>D", fzflua.lsp_typedefs, { desc = "Type [D]efinition" })
vim.keymap.set("n", "<leader>ca", fzflua.lsp_code_actions, {desc = "Code [A]ctions"})
