require('which-key').add {
	{ "<leader>c",   group = "[C]ode" },
	{ "<leader>c_",  hidden = true },
	{ "<leader>d",   group = "[D]ocument" },
	{ "<leader>d_",  hidden = true },
	{ "<leader>db",  group = "[D]apToggleBreakPoint" },
	{ "<leader>dc",  group = "[D]apContinue" },
	{ "<leader>dt",  group = "[D]apUiToggle" },
	{ "<leader>dt_", desc = "" },
	{ "<leader>r",   group = "[R]ename" },
	{ "<leader>r_",  hidden = true },
	{ "<leader>s",   group = "[S]earch" },
	{ "<leader>s_",  hidden = true },
	{ "<leader>w",   group = "[W]orkspace" },
	{ "<leader>w_",  hidden = true },
	{ "<leader>fg",  group = "[T]elescope grep" },
}
