vim.o.termguicolors = true
require("config.lazy")
require("config.lsp")
require("config.general")
require("config.keybinds")
require("config.treesitter")
require("config.colorscheme")
require("oil").setup()
require("config.closetags")
require("config.dap")
require("config.whichkey")
require("config.mini")
require("config.gitsigns")
require("config.formatting")
require("config.dadbod")
require("config.nvim-tree")
require("config.fzf-lua")
require("config.textobjects")

vim.cmd(":Copilot disable")
